package seed

import "scam-directory/internal/models"

// CuratedTemplates returns 35 high-quality, diverse base scams covering the most
// common and currently active scam categories in South Africa.
func CuratedTemplates() []ScamTemplate {
	return []ScamTemplate{
		// Phishing
		{
			Type: "phishing", RiskLevel: models.RiskHigh, Verification: "VERIFIED",
			Title:           "Fake Banking Email Phishing Scam",
			Description:     "Victims receive an email that appears to be from a major South African bank, warning of suspicious activity or an account lock. The email contains a link to a cloned login page that steals credentials and card details.",
			Pattern:         "Impersonate trusted bank → create urgency about account lock → link to fake login page → capture credentials and OTPs → drain account.",
			ContactTypes:    []string{"email", "website"},
			TransferTypes:   []string{"bank_transfer"},
			Keywords:        []string{"phishing", "email", "bank", "login", "otp"},
			EstimatedLosses: 12000,
		},
		{
			Type: "phishing", RiskLevel: models.RiskHigh, Verification: "VERIFIED",
			Title:           "SARS E-Filing Refund Phishing Scam",
			Description:     "Scammers send emails and SMSes claiming a SARS tax refund is pending. A link leads to a fake SARS eFiling site that harvests login credentials, banking details, and ID numbers.",
			Pattern:         "Pretend to be SARS → promise tax refund → fake login page → harvest ID, banking and login details → financial theft or identity misuse.",
			ContactTypes:    []string{"email", "sms", "website"},
			TransferTypes:   []string{"bank_transfer"},
			Keywords:        []string{"sars", "refund", "efiling", "tax"},
			EstimatedLosses: 8500,
		},
		{
			Type: "phishing", RiskLevel: models.RiskMedium, Verification: "VERIFIED",
			Title:           "Courier Delivery Failed Phishing Scam",
			Description:     "Victims receive an email or SMS saying a parcel could not be delivered. A link asks for a small redelivery fee and card details. The payment page is fake and the card is used for further fraudulent transactions.",
			Pattern:         "Fake courier notification → redelivery fee → capture card details → additional unauthorised charges.",
			ContactTypes:    []string{"email", "sms", "website"},
			TransferTypes:   []string{"bank_transfer", "mobile_money"},
			Keywords:        []string{"courier", "delivery", "parcel", "fee"},
			EstimatedLosses: 3500,
		},
		{
			Type: "phishing", RiskLevel: models.RiskHigh, Verification: "VERIFIED",
			Title:           "WhatsApp Web Login Phishing Scam",
			Description:     "Victims receive an email claiming their WhatsApp Web session will expire. A fake QR-code page asks for their phone number and OTP, allowing scammers to take over the account.",
			Pattern:         "Fake WhatsApp Web expiry → collect phone number and OTP → hijack WhatsApp → impersonate contacts.",
			ContactTypes:    []string{"email", "website"},
			TransferTypes:   []string{"mobile_money"},
			Keywords:        []string{"whatsapp", "web", "qr", "otp"},
			EstimatedLosses: 7000,
		},

		// Smishing
		{
			Type: "smishing", RiskLevel: models.RiskHigh, Verification: "VERIFIED",
			Title:           "Fake Bank SMS Smishing Scam",
			Description:     "Victims receive an SMS appearing to be from their bank, claiming a suspicious transaction. A link leads to a fake banking app login that captures credentials and OTPs.",
			Pattern:         "SMS impersonating bank → suspicious transaction alert → fake login link → credential theft.",
			ContactTypes:    []string{"sms", "website"},
			TransferTypes:   []string{"bank_transfer"},
			Keywords:        []string{"sms", "bank", "suspicious transaction"},
			EstimatedLosses: 9500,
		},
		{
			Type: "smishing", RiskLevel: models.RiskHigh, Verification: "VERIFIED",
			Title:           "SIM Swap Confirmation SMS Smishing Scam",
			Description:     "Victims receive an SMS asking them to confirm a SIM swap by replying with an OTP or pressing a link. Responding gives scammers control of the number and access to banking OTPs.",
			Pattern:         "Fake SIM swap confirmation → request OTP → hijack number → intercept banking codes.",
			ContactTypes:    []string{"sms"},
			TransferTypes:   []string{"bank_transfer"},
			Keywords:        []string{"sim swap", "otp", "mobile"},
			EstimatedLosses: 15000,
		},
		{
			Type: "smishing", RiskLevel: models.RiskHigh, Verification: "VERIFIED",
			Title:           "SARS SMS Refund Smishing Scam",
			Description:     "An SMS claims SARS has approved a refund and provides a link to a fake eFiling site. Victims enter login and banking details, leading to account takeovers.",
			Pattern:         "Fake SARS refund SMS → fake eFiling site → credential and banking theft.",
			ContactTypes:    []string{"sms", "website"},
			TransferTypes:   []string{"bank_transfer"},
			Keywords:        []string{"sars", "sms", "refund"},
			EstimatedLosses: 8000,
		},

		// Vishing
		{
			Type: "vishing", RiskLevel: models.RiskHigh, Verification: "VERIFIED",
			Title:           "Bank Fraud Department Vishing Scam",
			Description:     "Victims receive a phone call from someone claiming to be from their bank's fraud department. The caller uses spoofed caller ID and asks the victim to approve an Approve-it message or share an OTP to stop a fraudulent transaction.",
			Pattern:         "Spoofed bank caller ID → claim of fraud → request OTP or Approve-it → authorise theft.",
			ContactTypes:    []string{"phone"},
			TransferTypes:   []string{"bank_transfer"},
			Keywords:        []string{"vishing", "bank", "fraud department", "otp"},
			EstimatedLosses: 20000,
		},
		{
			Type: "vishing", RiskLevel: models.RiskHigh, Verification: "VERIFIED",
			Title:           "AI Voice Clone Family Emergency Vishing Scam",
			Description:     "Scammers use AI voice cloning to impersonate a family member in distress, claiming they have been arrested or injured and need money urgently. Victims transfer cash before verifying the call.",
			Pattern:         "AI voice clone of loved one → fake emergency → urgency → cash transfer.",
			ContactTypes:    []string{"phone"},
			TransferTypes:   []string{"cash", "mobile_money"},
			Keywords:        []string{"ai", "voice clone", "emergency", "family"},
			EstimatedLosses: 10000,
		},
		{
			Type: "vishing", RiskLevel: models.RiskHigh, Verification: "VERIFIED",
			Title:           "SARS Audit Threat Vishing Scam",
			Description:     "A caller impersonates a SARS official and threatens legal action or arrest for unpaid taxes. Victims are pressured to pay a settlement immediately to avoid prosecution.",
			Pattern:         "Fake SARS official → arrest or audit threat → demand immediate payment.",
			ContactTypes:    []string{"phone"},
			TransferTypes:   []string{"bank_transfer", "mobile_money"},
			Keywords:        []string{"sars", "audit", "arrest", "tax"},
			EstimatedLosses: 12000,
		},

		// SIM Swap
		{
			Type: "sim-swap", RiskLevel: models.RiskHigh, Verification: "VERIFIED",
			Title:           "SIM Swap Mobile Banking Fraud",
			Description:     "Fraudsters gather personal information through phishing or data breaches, then convince a mobile network to port the victim's number to a new SIM. They intercept banking OTPs and drain accounts within minutes.",
			Pattern:         "Harvest personal info → impersonate victim at network store → port number to new SIM → receive banking OTPs → transfer funds.",
			ContactTypes:    []string{"phone", "sms"},
			TransferTypes:   []string{"bank_transfer"},
			Keywords:        []string{"sim swap", "mobile banking", "otp"},
			EstimatedLosses: 25000,
		},
		{
			Type: "sim-swap", RiskLevel: models.RiskHigh, Verification: "VERIFIED",
			Title:           "Social Media SIM Swap Takeover",
			Description:     "Scammers obtain enough information from social media profiles to perform a SIM swap, then use the hijacked number to reset passwords and access bank, email, and social media accounts.",
			Pattern:         "Social media reconnaissance → SIM swap → password reset on accounts → theft and impersonation.",
			ContactTypes:    []string{"phone"},
			TransferTypes:   []string{"bank_transfer", "mobile_money"},
			Keywords:        []string{"sim swap", "social media", "takeover"},
			EstimatedLosses: 18000,
		},
		{
			Type: "sim-swap", RiskLevel: models.RiskHigh, Verification: "VERIFIED",
			Title:           "OTP Interception via SIM Swap",
			Description:     "After taking over a victim's number, scammers use intercepted OTPs to authorise large transfers and new beneficiaries on banking apps. Victims often only notice when their phone loses signal.",
			Pattern:         "SIM swap → OTP interception → add beneficiaries → transfer funds.",
			ContactTypes:    []string{"sms", "phone"},
			TransferTypes:   []string{"bank_transfer"},
			Keywords:        []string{"sim swap", "otp", "interception"},
			EstimatedLosses: 30000,
		},

		// Romance Scams
		{
			Type: "romance-scam", RiskLevel: models.RiskMedium, Verification: "VERIFIED",
			Title:           "Military Romance Scam",
			Description:     "A scammer poses as a deployed soldier or overseas professional on dating apps, building a relationship over weeks before asking for money for a fabricated emergency, travel, or customs fee.",
			Pattern:         "Fake profile on dating app → build emotional connection → emergency/travel excuse → request funds.",
			ContactTypes:    []string{"social_media", "whatsapp"},
			TransferTypes:   []string{"bank_transfer", "mobile_money"},
			Keywords:        []string{"romance", "military", "dating app"},
			EstimatedLosses: 45000,
		},
		{
			Type: "romance-scam", RiskLevel: models.RiskHigh, Verification: "VERIFIED",
			Title:           "Oil Rig Engineer Romance Scam",
			Description:     "The scammer claims to be an engineer on an offshore oil rig. They ask for money to pay for equipment, medical bills, or a flight home, promising to pay back once they return.",
			Pattern:         "Offshore worker persona → emotional bond → unexpected costs → repeated money requests.",
			ContactTypes:    []string{"social_media", "whatsapp"},
			TransferTypes:   []string{"bank_transfer", "crypto"},
			Keywords:        []string{"romance", "oil rig", "engineer"},
			EstimatedLosses: 80000,
		},
		{
			Type: "romance-scam", RiskLevel: models.RiskHigh, Verification: "VERIFIED",
			Title:           "Sextortion Romance Scam",
			Description:     "A scammer builds trust online, then tricks the victim into sharing intimate images or videos. They threaten to share the content unless money is sent, often repeatedly.",
			Pattern:         "Build trust online → obtain intimate content → blackmail → demand repeated payments.",
			ContactTypes:    []string{"social_media", "whatsapp"},
			TransferTypes:   []string{"mobile_money", "crypto"},
			Keywords:        []string{"romance", "sextortion", "blackmail"},
			EstimatedLosses: 25000,
		},

		// Investment / Crypto
		{
			Type: "investment-fraud", RiskLevel: models.RiskHigh, Verification: "VERIFIED",
			Title:           "Ponzi Scheme Promising Guaranteed Returns",
			Description:     "Victims are recruited through friends or social media to invest in a scheme offering guaranteed weekly returns. Early withdrawals are paid to build trust, but the platform eventually collapses and the operators disappear.",
			Pattern:         "Recruitment via friends/social media → guaranteed returns → early payouts → larger investments → collapse.",
			ContactTypes:    []string{"social_media", "whatsapp"},
			TransferTypes:   []string{"bank_transfer", "crypto"},
			Keywords:        []string{"investment", "ponzi", "guaranteed returns"},
			EstimatedLosses: 100000,
		},
		{
			Type: "investment-fraud", RiskLevel: models.RiskHigh, Verification: "VERIFIED",
			Title:           "Fake Forex Trading Platform Scam",
			Description:     "A social media 'trader' shows fake profits and invites victims to deposit funds into a proprietary trading platform. The platform shows fake gains but blocks withdrawals and eventually shuts down.",
			Pattern:         "Fake trader on social media → proprietary platform → fake profits → withdrawal blocked → platform gone.",
			ContactTypes:    []string{"social_media", "website"},
			TransferTypes:   []string{"bank_transfer", "crypto"},
			Keywords:        []string{"forex", "trading", "investment"},
			EstimatedLosses: 75000,
		},
		{
			Type: "crypto-scam", RiskLevel: models.RiskHigh, Verification: "VERIFIED",
			Title:           "Pig Butchering Crypto Scam",
			Description:     "Scammers build a relationship online, often romantic, then introduce a fake crypto investment. They guide victims to deposit increasing amounts until the platform disappears.",
			Pattern:         "Build trust online → introduce crypto investment → small gains → large deposit → platform collapses.",
			ContactTypes:    []string{"social_media", "whatsapp"},
			TransferTypes:   []string{"crypto"},
			Keywords:        []string{"crypto", "pig butchering", "investment"},
			EstimatedLosses: 150000,
		},
		{
			Type: "investment-fraud", RiskLevel: models.RiskMedium, Verification: "VERIFIED",
			Title:           "Deepfake Celebrity Investment Ad Scam",
			Description:     "Social media ads use deepfake videos of South African celebrities and business figures promoting a fake investment platform. Victims sign up and deposit money, but the platform is a scam.",
			Pattern:         "Deepfake celebrity endorsement → fake platform → victim deposits → funds stolen.",
			ContactTypes:    []string{"social_media", "website"},
			TransferTypes:   []string{"bank_transfer", "crypto"},
			Keywords:        []string{"deepfake", "celebrity", "investment"},
			EstimatedLosses: 40000,
		},

		// Job Scams
		{
			Type: "job-scam", RiskLevel: models.RiskMedium, Verification: "VERIFIED",
			Title:           "Work-From-Home Data Entry Job Scam",
			Description:     "A job ad promises easy work-from-home data entry with high pay. Applicants are asked to pay a registration fee, training fee, or buy special software. The job does not exist.",
			Pattern:         "Attractive job ad → request registration/training fee → fee paid → no work provided.",
			ContactTypes:    []string{"email", "website"},
			TransferTypes:   []string{"bank_transfer", "mobile_money"},
			Keywords:        []string{"job", "work from home", "data entry"},
			EstimatedLosses: 2500,
		},
		{
			Type: "job-scam", RiskLevel: models.RiskHigh, Verification: "VERIFIED",
			Title:           "Money Mule 'Financial Assistant' Job Scam",
			Description:     "A job ad offers a role as a financial assistant or payments processor. The 'employee' is asked to receive and forward money through their own bank account. The money is proceeds of crime and the account holder is exposed to legal action.",
			Pattern:         "Financial assistant job → receive funds into personal account → forward to third party → money laundering.",
			ContactTypes:    []string{"email", "whatsapp"},
			TransferTypes:   []string{"bank_transfer"},
			Keywords:        []string{"job", "money mule", "financial assistant"},
			EstimatedLosses: 50000,
		},
		{
			Type: "job-scam", RiskLevel: models.RiskMedium, Verification: "VERIFIED",
			Title:           "Overseas Job Offer Scam",
			Description:     "Victims are offered well-paying jobs abroad. They are asked to pay for visas, medical checks, and flights. The job offer and agency are fake.",
			Pattern:         "Overseas job offer → visa/medical/flight fees → payment made → no job or travel documents.",
			ContactTypes:    []string{"email", "phone"},
			TransferTypes:   []string{"bank_transfer"},
			Keywords:        []string{"job", "overseas", "visa"},
			EstimatedLosses: 15000,
		},

		// Online Shopping / Marketplace
		{
			Type: "online-shopping", RiskLevel: models.RiskMedium, Verification: "VERIFIED",
			Title:           "Fake Online Electronics Store Scam",
			Description:     "A professional-looking website advertises popular electronics at below-market prices. Orders are placed but never delivered, and the site is taken offline after collecting payments.",
			Pattern:         "Fake store with low prices → order and payment → no delivery → site disappears.",
			ContactTypes:    []string{"website", "email"},
			TransferTypes:   []string{"bank_transfer", "crypto"},
			Keywords:        []string{"online shopping", "electronics", "fake store"},
			EstimatedLosses: 6000,
		},
		{
			Type: "online-shopping", RiskLevel: models.RiskMedium, Verification: "VERIFIED",
			Title:           "Facebook Marketplace Fake Seller Scam",
			Description:     "A seller on Facebook Marketplace requests a deposit to reserve an item. After payment, they block the buyer and never deliver the item. The seller profile was recently created and uses stolen photos.",
			Pattern:         "Marketplace listing → deposit request → payment → seller blocks buyer.",
			ContactTypes:    []string{"social_media", "whatsapp"},
			TransferTypes:   []string{"mobile_money", "bank_transfer"},
			Keywords:        []string{"marketplace", "facebook", "deposit"},
			EstimatedLosses: 4000,
		},
		{
			Type: "online-shopping", RiskLevel: models.RiskMedium, Verification: "VERIFIED",
			Title:           "Overpayment Refund Marketplace Scam",
			Description:     "A buyer on a marketplace claims to have overpaid and sends a fake proof of payment. They ask the seller to refund the difference. The original payment never clears, and the seller loses the refund amount.",
			Pattern:         "Fake overpayment screenshot → request refund difference → seller refunds → original payment fake/reversed.",
			ContactTypes:    []string{"social_media", "whatsapp"},
			TransferTypes:   []string{"mobile_money", "bank_transfer"},
			Keywords:        []string{"marketplace", "overpayment", "refund"},
			EstimatedLosses: 5000,
		},

		// Advance Fee / Lottery
		{
			Type: "advance-fee", RiskLevel: models.RiskMedium, Verification: "VERIFIED",
			Title:           "Inheritance Advance Fee Scam",
			Description:     "A scammer informs the victim that they are the beneficiary of a large inheritance from a distant relative. To release the funds, the victim must pay legal fees, taxes, or bribes upfront. The inheritance does not exist.",
			Pattern:         "Unexpected inheritance news → fees/taxes to release → repeated payments → no inheritance.",
			ContactTypes:    []string{"email"},
			TransferTypes:   []string{"bank_transfer"},
			Keywords:        []string{"inheritance", "advance fee", "419"},
			EstimatedLosses: 20000,
		},
		{
			Type: "lottery-scam", RiskLevel: models.RiskMedium, Verification: "VERIFIED",
			Title:           "Fake Lotto Winnings Scam",
			Description:     "Victims receive an SMS or email saying they have won a lottery or competition they never entered. To claim the prize, they must pay a processing fee or provide banking details. The prize is fake.",
			Pattern:         "Unexpected win notification → processing fee or details → payment → no prize.",
			ContactTypes:    []string{"sms", "email"},
			TransferTypes:   []string{"mobile_money", "bank_transfer"},
			Keywords:        []string{"lottery", "winnings", "prize"},
			EstimatedLosses: 3500,
		},
		{
			Type: "advance-fee", RiskLevel: models.RiskMedium, Verification: "VERIFIED",
			Title:           "Loan Approval Fee Scam",
			Description:     "A fake lender approves a loan quickly and asks for an upfront admin, insurance, or attorney fee. Once the fee is paid, the loan never arrives and the lender disappears.",
			Pattern:         "Quick loan approval → upfront fee → fee paid → loan never disbursed.",
			ContactTypes:    []string{"email", "phone"},
			TransferTypes:   []string{"bank_transfer", "mobile_money"},
			Keywords:        []string{"loan", "advance fee", "admin fee"},
			EstimatedLosses: 5000,
		},

		// Rental Scams
		{
			Type: "rental-scam", RiskLevel: models.RiskMedium, Verification: "VERIFIED",
			Title:           "Fake Rental Deposit Scam",
			Description:     "A scammer posts a rental property at a below-market price on classified sites. They claim to be overseas and ask for a deposit to secure the property. After payment, the listing is removed and the scammer is unreachable.",
			Pattern:         "Attractive rental listing → overseas landlord → deposit to secure → listing removed.",
			ContactTypes:    []string{"email", "whatsapp"},
			TransferTypes:   []string{"bank_transfer"},
			Keywords:        []string{"rental", "deposit", "property"},
			EstimatedLosses: 8000,
		},
		{
			Type: "rental-scam", RiskLevel: models.RiskMedium, Verification: "VERIFIED",
			Title:           "Stolen Property Photos Rental Scam",
			Description:     "Scammers copy legitimate property listings and repost them with lower rent. They arrange viewings by email only and demand a deposit before meeting. The property is not actually available.",
			Pattern:         "Copy legitimate listing → lower rent → email-only contact → deposit before viewing → not available.",
			ContactTypes:    []string{"email", "social_media"},
			TransferTypes:   []string{"bank_transfer"},
			Keywords:        []string{"rental", "stolen photos", "property"},
			EstimatedLosses: 7000,
		},

		// Tech Support
		{
			Type: "tech-support-scam", RiskLevel: models.RiskMedium, Verification: "VERIFIED",
			Title:           "Microsoft Virus Alert Pop-Up Scam",
			Description:     "A pop-up on a website claims the computer is infected and provides a phone number for 'Microsoft support'. The fake technician requests remote access and charges for unnecessary software or services.",
			Pattern:         "Fake virus pop-up → call support number → remote access → charge for fake services.",
			ContactTypes:    []string{"phone", "website"},
			TransferTypes:   []string{"bank_transfer"},
			Keywords:        []string{"tech support", "virus", "microsoft"},
			EstimatedLosses: 4000,
		},
		{
			Type: "tech-support-scam", RiskLevel: models.RiskHigh, Verification: "VERIFIED",
			Title:           "Antivirus Subscription Renewal Scam",
			Description:     "An email or call claims an antivirus subscription is renewing at a high price. The fake support agent offers a refund if the victim provides remote access or banking details. Money is stolen instead of refunded.",
			Pattern:         "Fake renewal notice → refund offer → remote access or banking details → money stolen.",
			ContactTypes:    []string{"email", "phone"},
			TransferTypes:   []string{"bank_transfer"},
			Keywords:        []string{"tech support", "antivirus", "refund"},
			EstimatedLosses: 6000,
		},

		// Identity Theft
		{
			Type: "identity-theft", RiskLevel: models.RiskHigh, Verification: "VERIFIED",
			Title:           "ID Document Theft for Loan Applications",
			Description:     "Scammers collect copies of ID documents, payslips, and bank statements through fake job or rental applications. They use these to apply for loans, credit cards, and accounts in the victim's name.",
			Pattern:         "Collect ID documents via fake application → use for credit applications → victim discovers debt later.",
			ContactTypes:    []string{"email"},
			TransferTypes:   []string{"bank_transfer"},
			Keywords:        []string{"identity theft", "loan", "documents"},
			EstimatedLosses: 40000,
		},
		{
			Type: "identity-theft", RiskLevel: models.RiskHigh, Verification: "VERIFIED",
			Title:           "SIM RICA ID Harvesting Scam",
			Description:     "Fraudsters pose as mobile network agents doing RICA verification and ask for ID documents and photos. The information is used to commit identity theft and facilitate SIM swaps.",
			Pattern:         "Fake RICA agent → request ID and selfie → identity theft or SIM swap.",
			ContactTypes:    []string{"phone", "whatsapp"},
			TransferTypes:   []string{"mobile_money"},
			Keywords:        []string{"identity theft", "rica", "id"},
			EstimatedLosses: 15000,
		},

		// WhatsApp Impersonation
		{
			Type: "smishing", RiskLevel: models.RiskHigh, Verification: "VERIFIED",
			Title:           "WhatsApp Friend in Need Scam",
			Description:     "A scammer hacks or clones a friend's WhatsApp account and sends messages asking for urgent financial help. Victims transfer money before realising the friend was impersonated.",
			Pattern:         "Compromise WhatsApp account → message contacts for urgent help → collect money.",
			ContactTypes:    []string{"whatsapp"},
			TransferTypes:   []string{"mobile_money", "bank_transfer"},
			Keywords:        []string{"whatsapp", "impersonation", "friend in need"},
			EstimatedLosses: 5000,
		},
		{
			Type: "smishing", RiskLevel: models.RiskHigh, Verification: "VERIFIED",
			Title:           "WhatsApp Business Account Takeover Scam",
			Description:     "A business owner receives a WhatsApp message claiming to be from WhatsApp support asking for a verification code. The code is used to take over the business account and scam customers.",
			Pattern:         "Fake WhatsApp support → request verification code → account takeover → scam customers.",
			ContactTypes:    []string{"whatsapp"},
			TransferTypes:   []string{"mobile_money"},
			Keywords:        []string{"whatsapp", "business", "takeover"},
			EstimatedLosses: 10000,
		},

		// Courier / Delivery
		{
			Type: "phishing", RiskLevel: models.RiskMedium, Verification: "VERIFIED",
			Title:           "Courier Customs Fee Scam",
			Description:     "An email or SMS claims an international parcel is held at customs and requires a small customs or clearance fee. The payment link is fake and steals card details.",
			Pattern:         "Parcel held at customs → small clearance fee → fake payment link → card theft.",
			ContactTypes:    []string{"email", "sms", "website"},
			TransferTypes:   []string{"bank_transfer"},
			Keywords:        []string{"courier", "customs", "parcel"},
			EstimatedLosses: 3000,
		},

		// Social Media
		{
			Type: "phishing", RiskLevel: models.RiskMedium, Verification: "VERIFIED",
			Title:           "Instagram Verification Badge Scam",
			Description:     "An account claiming to be Instagram support offers a verified badge for a fee. Victims pay but never receive verification and lose control of their account details.",
			Pattern:         "Fake Instagram support → paid verification offer → collect fee and account details → no badge.",
			ContactTypes:    []string{"social_media"},
			TransferTypes:   []string{"mobile_money", "crypto"},
			Keywords:        []string{"instagram", "verification", "badge"},
			EstimatedLosses: 3000,
		},
		{
			Type: "phishing", RiskLevel: models.RiskMedium, Verification: "VERIFIED",
			Title:           "TikTok Monetisation Scam",
			Description:     "Creators receive messages claiming they qualify for TikTok monetisation or a creator fund. They are asked to pay a registration fee or provide login details. The funds and accounts are stolen.",
			Pattern:         "Fake TikTok monetisation → registration fee or login → payment/account theft.",
			ContactTypes:    []string{"social_media"},
			TransferTypes:   []string{"mobile_money"},
			Keywords:        []string{"tiktok", "monetisation", "creator"},
			EstimatedLosses: 2500,
		},
	}
}
